name: Sonar Workflow

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        description: "Sonar token for access to SonarCloud"
        required: true

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download workspace artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage-file
          path: ./coverage

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.language=go
            -Dsonar.coverage.exclusions=**/tests/**,**/*_test.go
            -Dsonar.go.coverage.reportPaths=./coverage/cleaned-coverage.out